import { Montserrat } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const unbounded = localFont({
  src: [
    {
      path: '../../public/fonts/unbounded-v8-cyrillic_latin-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/unbounded-v8-cyrillic_latin-700.woff2',
      weight: '700',
      style: 'normal',
    }
  ]
});

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.className} ${montserrat.variable} antialiased w-full bg-dark font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
